
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "David Lu", email = "davidlu1001@gmail.com"},
]
dependencies = [
    "diagrams>=0.23.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}

